name: main

on:
  push:
  pull_request:
  schedule:
    - cron: "0 2,14 * * *"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install nightly
        run: rustup install nightly
      # install master installer
      - name: install rustup-toolchain-install-master
      #  run: cargo install --debug --git https://github.com/kennytm/rustup-toolchain-install-master
        run: cargo install --debug rustup-toolchain-install-master
      - name: install master toolchain
        run: rustup-toolchain-install-master -f -n master -c rustc-dev llvm-tools rust-src clippy rustfmt
      - name: make master the default toolchain
        run: rustup default master
      - name: rustc --version
        run: rustc --version --verbose
      - name: build
        run: cargo build --release
      - name: run glacier2
        run: cargo run --release
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ices/* || true
          git add fixed/* || true
          git commit -am "update ices" || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.repo_untouched.outputs.exit_code == 0
        with:
          github_token: ${{ secrets.GLACIER_SECRET }}
          branch: ${{ github.ref }}
